/*
    Hotkeys
*/

+F12::
    Gosub, ExitGracefully
return

ActivateWindow1:
    API.GetWindow(1).Activate()
return
ActivateWindow2:
    API.GetWindow(2).Activate()
return
ActivateWindow3:
    API.GetWindow(3).Activate()
return
ActivateWindow4:
    API.GetWindow(4).Activate()
return
ActivateWindow5:
    API.GetWindow(5).Activate()
return
ActivateWindow6:
    API.GetWindow(6).Activate()
return
ActivateWindow7:
    API.GetWindow(7).Activate()
return
ActivateWindow8:
    API.GetWindow(8).Activate()
return
ActivateWindow9:
    API.GetWindow(9).Activate()
return
ActivateWindow10:
    API.GetWindow(10).Activate()
return
ActivateWindow11:
    API.GetWindow(11).Activate()
return
ActivateWindow12:
    API.GetWindow(12).Activate()
return
